version: 2
models:
  - name: inter_movies_genre
    columns:
      - name: tmdb_id
        description: ""
        meta:
          dimension:
            type: number
      - name: release_year
        description: ""
        meta:
          dimension:
            type: number
      - name: genre_name
        description: ""
        meta:
          dimension:
            type: string
  - name: inter_movies_genre_pivot
    columns:
      - name: release_year
        description: ""
        meta:
          dimension:
            type: number
      - name: comedy
        description: ""
        meta:
          dimension:
            type: number
      - name: war
        description: ""
        meta:
          dimension:
            type: number
      - name: science_fiction
        description: ""
        meta:
          dimension:
            type: number
      - name: horror
        description: ""
        meta:
          dimension:
            type: number
      - name: action
        description: ""
        meta:
          dimension:
            type: number
      - name: crime
        description: ""
        meta:
          dimension:
            type: number
      - name: drama
        description: ""
        meta:
          dimension:
            type: number
      - name: animation
        description: ""
        meta:
          dimension:
            type: number
      - name: history
        description: ""
        meta:
          dimension:
            type: number
      - name: western
        description: ""
        meta:
          dimension:
            type: number
      - name: family
        description: ""
        meta:
          dimension:
            type: number
      - name: romance
        description: ""
        meta:
          dimension:
            type: number
      - name: music
        description: ""
        meta:
          dimension:
            type: number
      - name: thriller
        description: ""
        meta:
          dimension:
            type: number
      - name: mystery
        description: ""
        meta:
          dimension:
            type: number
      - name: tv_movie
        description: ""
        meta:
          dimension:
            type: number
      - name: documentary
        description: ""
        meta:
          dimension:
            type: number
      - name: fantasy
        description: ""
        meta:
          dimension:
            type: number
      - name: adventure
        description: ""
        meta:
          dimension:
            type: number
  - name: inter_dim_genre
    columns:
      - name: tv_series_id
        description: ""
        meta:
          dimension:
            type: number
      - name: genre_name
        description: ""
        meta:
          dimension:
            type: string
  - name: combine_movies_db
    columns:
      - name: imdb_id
        description: ""
        meta:
          dimension:
            type: string
      - name: tmdb_id
        description: ""
        meta:
          dimension:
            type: number
      - name: tmdb_title
        description: ""
        meta:
          dimension:
            type: string
      - name: status
        description: ""
        meta:
          dimension:
            type: string
      - name: overview
        description: ""
        meta:
          dimension:
            type: string
      - name: tagline
        description: ""
        meta:
          dimension:
            type: string
      - name: keywords
        description: ""
        meta:
          dimension:
            type: string
      - name: video
        description: ""
        meta:
          dimension:
            type: boolean
      - name: genre_names
        description: ""
        meta:
          dimension:
            type: string
      - name: revenue
        description: ""
        meta:
          dimension:
            type: number
      - name: budget
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_rated
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_director
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_writer
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_actors
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_plot
        description: ""
        meta:
          dimension:
            type: string
      - name: tmdb_original_language
        description: ""
        meta:
          dimension:
            type: string
      - name: tmdb_spoken_language
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_language
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_country
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_awards
        description: ""
        meta:
          dimension:
            type: string
      - name: tmdb_production_company
        description: ""
        meta:
          dimension:
            type: string
      - name: tmdb_production_country
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_production
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_dvd
        description: ""
        meta:
          dimension:
            type: string
      - name: tmdb_release_date
        description: ""
        meta:
          dimension:
            type: date
      - name: omdb_release_year
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_release_date
        description: ""
        meta:
          dimension:
            type: date
      - name: tmdb_runtime
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_runtime
        description: ""
        meta:
          dimension:
            type: number
      - name: tmdb_vote_average
        description: ""
        meta:
          dimension:
            type: number
      - name: tmdb_vote_count
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_metascore
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_ratings
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_votes
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_box_office
        description: ""
        meta:
          dimension:
            type: number
  - name: clean_movies
    columns:
      - name: imdb_id
        description: ""
        meta:
          dimension:
            type: string
      - name: tmdb_id
        description: ""
        meta:
          dimension:
            type: number
      - name: tmdb_title
        description: ""
        meta:
          dimension:
            type: string
      - name: status
        description: ""
        meta:
          dimension:
            type: string
      - name: overview
        description: ""
        meta:
          dimension:
            type: string
      - name: tagline
        description: ""
        meta:
          dimension:
            type: string
      - name: keywords
        description: ""
        meta:
          dimension:
            type: string
      - name: video
        description: ""
        meta:
          dimension:
            type: boolean
      - name: genre_names
        description: ""
        meta:
          dimension:
            type: string
      - name: revenue
        description: ""
        meta:
          dimension:
            type: number
      - name: budget
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_rated
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_director
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_writer
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_actors
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_plot
        description: ""
        meta:
          dimension:
            type: string
      - name: tmdb_original_language
        description: ""
        meta:
          dimension:
            type: string
      - name: tmdb_spoken_language
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_language
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_country
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_awards
        description: ""
        meta:
          dimension:
            type: string
      - name: tmdb_production_company
        description: ""
        meta:
          dimension:
            type: string
      - name: tmdb_production_country
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_production
        description: ""
        meta:
          dimension:
            type: string
      - name: omdb_dvd
        description: ""
        meta:
          dimension:
            type: string
      - name: tmdb_release_date
        description: ""
        meta:
          dimension:
            type: date
      - name: omdb_release_year
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_release_date
        description: ""
        meta:
          dimension:
            type: date
      - name: tmdb_runtime
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_runtime
        description: ""
        meta:
          dimension:
            type: number
      - name: tmdb_vote_average
        description: ""
        meta:
          dimension:
            type: number
      - name: tmdb_vote_count
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_metascore
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_ratings
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_votes
        description: ""
        meta:
          dimension:
            type: number
      - name: omdb_box_office
        description: ""
        meta:
          dimension:
            type: number
      - name: release_date
        description: ""
        meta:
          dimension:
            type: date
      - name: release_year
        description: ""
        meta:
          dimension:
            type: number
  - name: inter_num_movies_per_year
    columns:
      - name: release_year
        description: ""
        meta:
          dimension:
            type: number
      - name: total_movies
        description: ""
        meta:
          dimension:
            type: number
