name: "paradime_movie_challenge"
version: "1.0.0"
config-version: 2

profile: "paradime-movie-challenge"

vars:
  # Analyze movies released for the period below:
  start_year: 1984
  end_year: 2023

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

query-comment:
  comment: '{{ get_query_comment(node) }}'
  append: true

models:
  paradime_movie_challenge: 
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view 
    marts: 
      +tags:
      - "lightdash"
      +schema: marts
      +materialized: table 