version: 2
models:
  - name: stg_omdb_movies
    description: |
      Staging model for storing information about movies from the OMDB API.

    columns:
      - name: imdb_id
        description: |
          {{ doc("stg_omdb_movies__imdb_id") }}
        meta:
          dimension:
            type: string
        tests:
          - unique
          - not_null

      - name: title
        description: |
          {{ doc("stg_omdb_movies__title") }}
        meta:
          dimension:
            type: string

      - name: director
        description: |
          {{ doc("stg_omdb_movies__director") }}
        meta:
          dimension:
            type: string

      - name: writer
        description: |
          {{ doc("stg_omdb_movies__writer") }}
        meta:
          dimension:
            type: string

      - name: actors
        description: |
          {{ doc("stg_omdb_movies__actors") }}
        meta:
          dimension:
            type: string

      - name: genre
        description: |
          {{ doc("stg_omdb_movies__genre") }}
        meta:
          dimension:
            type: string

      - name: language
        description: |
          {{ doc("stg_omdb_movies__language") }}
        meta:
          dimension:
            type: string

      - name: country
        description: |
          {{ doc("stg_omdb_movies__country") }}
        meta:
          dimension:
            type: string

      - name: type
        description: |
          {{ doc("stg_omdb_movies__type") }}
        meta:
          dimension:
            type: string

      - name: plot
        description: |
          {{ doc("stg_omdb_movies__plot") }}
        meta:
          dimension:
            type: string

      - name: rated
        description: |
          {{ doc("stg_omdb_movies__rated") }}
        meta:
          dimension:
            type: string

      - name: ratings
        description: |
          {{ doc("stg_omdb_movies__ratings") }}
        meta:
          dimension:
            type: string

      - name: metascore
        description: |
          {{ doc("stg_omdb_movies__metascore") }}
        meta:
          dimension:
            type: number

      - name: imdb_rating
        description: |
          {{ doc("stg_omdb_movies__imdb_rating") }}
        meta:
          dimension:
            type: number

      - name: imdb_votes
        description: |
          {{ doc("stg_omdb_movies__imdb_votes") }}
        meta:
          dimension:
            type: number

      - name: released_date
        description: |
          {{ doc("stg_omdb_movies__released_date") }}
        meta:
          dimension:
            type: date

      - name: release_year
        description: |
          {{ doc("stg_omdb_movies__release_year") }}
        meta:
          dimension:
            type: number

      - name: runtime
        description: |
          {{ doc("stg_omdb_movies__runtime") }}
        meta:
          dimension:
            type: number

      - name: dvd
        description: |
          {{ doc("stg_omdb_movies__dvd") }}
        meta:
          dimension:
            type: string

      - name: box_office
        description: |
          {{ doc("stg_omdb_movies__box_office") }}
        meta:
          dimension:
            type: number

      - name: poster
        description: |
          {{ doc("stg_omdb_movies__poster") }}
        meta:
          dimension:
            type: string

      - name: production
        description: |
          {{ doc("stg_omdb_movies__production") }}
        meta:
          dimension:
            type: string

      - name: website
        description: |
          {{ doc("stg_omdb_movies__website") }}
        meta:
          dimension:
            type: string

      - name: awards
        description: |
          {{ doc("stg_omdb_movies__awards") }}
        meta:
          dimension:
            type: string

      - name: tmdb_id
        description: |
          {{ doc("stg_omdb_movies__tmdb_id") }}
        meta:
          dimension:
            type: number

  
  - name: stg_tmdb_tv_series
    columns:
      - name: id
        description: Unique identifier for each TV show.
        meta:
          dimension:
            type: number
      - name: name
        description: Title of the TV show.
        meta:
          dimension:
            type: string
      - name: overview
        description: Brief description or summary of the TV show.
        meta:
          dimension:
            type: string
      - name: tagline
        description: Catchphrase or memorable line associated with the TV show.
        meta:
          dimension:
            type: string
      - name: genre_names
        description: Genres associated with the TV show.
        meta:
          dimension:
            type: string
      - name: created_by_names
        description: Names of individuals or entities credited for creating the TV show.
        meta:
          dimension:
            type: string
      - name: original_language
        description: Original language in which the TV show was produced.
        meta:
          dimension:
            type: string
      - name: status
        description: Current status of the TV show (e.g., returning series, ended, cancelled, etc.).
        meta:
          dimension:
            type: string
      - name: in_production
        description: Indicates if the TV show is currently in production.
        meta:
          dimension:
            type: boolean
      - name: first_air_date
        description: Date when the TV show was first aired.
        meta:
          dimension:
            type: date
      - name: last_air_date
        description: Date when the TV show was last aired.
        meta:
          dimension:
            type: date
      - name: number_of_seasons
        description: Number of seasons in the TV show.
        meta:
          dimension:
            type: number
      - name: number_of_episodes
        description: Number of episodes in the TV show.
        meta:
          dimension:
            type: number
      - name: vote_average
        description: Average vote or rating given by viewers.
        meta:
          dimension:
            type: number
      - name: vote_count
        description: Total number of votes received by the TV show.
        meta:
          dimension:
            type: number
      - name: popularity
        description: Popularity score of the TV show.
        meta:
          dimension:
            type: number
      - name: poster_path
        description: URL path of the poster image for the TV show.
        meta:
          dimension:
            type: string
      - name: production_company_names
        description: Names of production companies associated with the TV show.
        meta:
          dimension:
            type: string


  - name: stg_tmdb_movies
    description: |
      Staging model for storing information about movies from the TMDB API.

    columns:
      - name: tmdb_id
        description: |
          {{ doc("stg_tmdb_movies__tmdb_id") }}
        meta:
          dimension:
            type: number
        tests:
          - unique
          - not_null

      - name: title
        description: |
          {{ doc("stg_tmdb_movies__title") }}
        meta:
          dimension:
            type: string

      - name: overview
        description: |
          {{ doc("stg_tmdb_movies__overview") }}
        meta:
          dimension:
            type: string

      - name: tagline
        description: |
          {{ doc("stg_tmdb_movies__tagline") }}
        meta:
          dimension:
            type: string

      - name: spoken_languages
        description: |
          {{ doc("stg_tmdb_movies__spoken_languages") }}
        meta:
          dimension:
            type: string

      - name: original_language
        description: |
          {{ doc("stg_tmdb_movies__original_language") }}
        meta:
          dimension:
            type: string

      - name: keywords
        description: |
          {{ doc("stg_tmdb_movies__keywords") }}
        meta:
          dimension:
            type: string

      - name: status
        description: |
          {{ doc("stg_tmdb_movies__status") }}
        meta:
          dimension:
            type: string

      - name: video
        description: |
          {{ doc("stg_tmdb_movies__video") }}
        meta:
          dimension:
            type: boolean

      - name: vote_average
        description: |
          {{ doc("stg_tmdb_movies__vote_average") }}
        meta:
          dimension:
            type: number

      - name: budget
        description: |
          {{ doc("stg_tmdb_movies__budget") }}
        meta:
          dimension:
            type: number

      - name: revenue
        description: |
          {{ doc("stg_tmdb_movies__revenue") }}
        meta:
          dimension:
            type: number

      - name: runtime
        description: |
          {{ doc("stg_tmdb_movies__runtime") }}
        meta:
          dimension:
            type: number

      - name: release_date
        description: |
          {{ doc("stg_tmdb_movies__release_date") }}
        meta:
          dimension:
            type: date

      - name: belongs_to_collection
        description: |
          {{ doc("stg_tmdb_movies__belongs_to_collection") }}
        meta:
          dimension:
            type: string

      - name: poster_path
        description: |
          {{ doc("stg_tmdb_movies__poster_path") }}
        meta:
          dimension:
            type: string

      - name: backdrop_path
        description: |
          {{ doc("stg_tmdb_movies__backdrop_path") }}
        meta:
          dimension:
            type: string

      - name: homepage
        description: |
          {{ doc("stg_tmdb_movies__homepage") }}
        meta:
          dimension:
            type: string

      - name: imdb_id
        description: |
          {{ doc("stg_tmdb_movies__imdb_id") }}
        meta:
          dimension:
            type: string

      - name: original_title
        description: |
          {{ doc("stg_tmdb_movies__original_title") }}
        meta:
          dimension:
            type: string

      - name: vote_count
        description: |
          {{ doc("stg_tmdb_movies__vote_count") }}
        meta:
          dimension:
            type: number

      - name: genre_names
        description: |
          {{ doc("stg_tmdb_movies__genre_names") }}
        meta:
          dimension:
            type: string

      - name: production_company_names
        description: |
          {{ doc("stg_tmdb_movies__production_company_names") }}
        meta:
          dimension:
            type: string

      - name: production_country_names
        description: |
          {{ doc("stg_tmdb_movies__production_country_names") }}
        meta:
          dimension:
            type: string


  - name: stg_rotten_tomatoes
    description: |
      Staging model for storing information about movies from the rotten tomatoes API.

    columns:
      - name: rotten_tomatoes_id
        description: |
          {{ doc("stg_rotten_tomatoes__rotten_tomatoes_id") }}
        tests:
          - unique
          - not_null
  
      - name: title
        description: |
          {{ doc("stg_rotten_tomatoes__title") }}

      - name: audience_score
        description: |
          {{ doc("stg_rotten_tomatoes__audience_score") }}

      - name: tomato_meter
        description: |
          {{ doc("stg_rotten_tomatoes__tomato_meter") }}

      - name: runtime_minutes
        description: |
          {{ doc("stg_rotten_tomatoes__runtime_minutes") }}

      - name: genre
        description: |
          {{ doc("stg_rotten_tomatoes__genre") }}

      - name: box_office
        description: |
          {{ doc("stg_rotten_tomatoes__box_office") }}


  - name: stg_imdb_ratings
    description: |
      Staging model for storing information about movies from the IMDB API.

    columns:
      - name: imdb_title_id
        description: |
          {{ doc("stg_imdb_ratings__imdb_title_id") }}
        tests:
          - unique
          - not_null
  
      - name: imdb_rating
        description: |
          {{ doc("stg_imdb_ratings__imdb_rating") }}

      - name: number_of_votes
        description: |
          {{ doc("stg_imdb_ratings__number_of_votes") }}