sources:
  - name: PARADIME_MOVIE_CHALLENGE
    database: MOVIE_CHALLENGE
    schema: PUBLIC
    tables:
      - name: TMDB_MOVIES
      - name: OMDB_MOVIES
      - name: TMDB_TV_SERIES
  - name: PARADIME_MOVIE_CHALLENGE_EXTRA
    database: PHILIPSONGCHRFJ_ANALYTICS
    schema: STAGING
    tables:
      - name: INFLATION_2023
      - name: TMDB_EX
  - name: PARADIME_MOVIE_CHALLENGE_FINAL
    database: PHILIPSONGCHRFJ_ANALYTICS
    schema: INTERMEDIATE
    tables:
      - name: OMDB_INFLATION_ADJUSTED
  - name: PRODUCTION_COMPANIES_OVERALL
    database: PHILIPSONGCHRFJ_ANALYTICS
    schema: INTERMEDIATE
    tables:
      - name: production_companies      
