sources:
  - name: PARADIME_MOVIE_CHALLENGE
    database: MOVIE_CHALLENGE
    schema: PUBLIC
    tables:
      - name: TMDB_MOVIES
      - name: OMDB_MOVIES
      - name: TMDB_TV_SERIES
  - name: PARADIME_MOVIE_CHALLENGE_EXTRA
    database: PHILIPSONGCHRFJ_ANALYTICS
    schema: STAGING
    tables:
      - name: INFLATION_2023
  - name: PARADIME_MOVIE_CHALLENGE_FINAL
    database: PHILIPSONGCHRFJ_ANALYTICS
    schema: INTERMEDIATE
    tables:
      - name: OMDB_INFLATION_ADJUSTED
