sources:
  - name: PARADIME_MOVIE_CHALLENGE
    database: MOVIE_CHALLENGE
    schema: PUBLIC
    tables:
      - name: TMDB_MOVIES
      - name: OMDB_MOVIES

  - name: MOVIES_ADDITIONAL
    database: LETICIABUENO8DKEQ_ANALYTICS
    schema: RAW
    tables:
      - name: IMDB_CREW
      - name: IMDB_MOVIES
      - name: IMDB_PEOPLE
      - name: IMDB_MOVIES_PEOPLE
      - name: IMDB_RATINGS
      - name: ACADEMY_AWARDS
      - name: CONSUMER_PRICE_INDEX