sources:
  - name: PARADIME_MOVIE_CHALLENGE
    database: MOVIE_CHALLENGE
    schema: PUBLIC
    tables:
      - name: OMDB_MOVIES
      - name: TMDB_MOVIES      

  - name: MOVIES_ADDITIONAL
    database: LETICIABUENO8DKEQ_ANALYTICS
    schema: RAW
    tables:
      - name: CONSUMER_PRICE_INDEX
      - name: ACADEMY_AWARDS