version: 2
models:
  - name: production_score
    columns:
      - name: production_company
        description: ""
        meta:
          dimension:
            type: string
      - name: movies_made
        description: ""
        meta:
          dimension:
            type: number
      - name: total_revenue
        description: ""
        meta:
          dimension:
            type: number
      - name: film_ct_score
        description: ""
        meta:
          dimension:
            type: number
            hidden: true
          metrics:
            film_count_score:
              type: sum            
      - name: film_raw_rev_score
        description: ""
        meta:
          dimension:
            type: number
            hidden: true
          metrics:
            film_revenue_score:
              type: sum                 
      - name: combo_score
        description: ""
        meta:
          dimension:
            type: number
            hidden: true
          metrics:
            total_score:
              type: sum                 
