version: 2

models:
  - name: production_companies
    description: ""
    columns:
      - name: production_company
        description: ""
        meta:
          dimension:
            type: string
      - name: release_date
        description: ""
        meta:
          dimension:
            type: date
            time_intervals: ["YEAR"]
      - name: budget_adj
        description: ""
        meta:
          dimension:
            type: number
          metrics:
            total_budget_adj:
              type: sum
              format: usd
            average_budjet_adj:
              type: average
              format: usd
      - name: revenue_adj
        description: ""
        meta:
          dimension:
            type: number
          metrics:
            total_revenue_adj:
              type: sum
              format: usd
            average_revenue_adj:
              type: average
              format: usd
      - name: tmdb_id
        description: ""
        meta:
          dimension:
            type: number
          metrics:
            total_movies:
              type: count_distinct

