version: 2
models:
  - name: stg_imdb__movie_people
    description: Join movies and people info for each movie provided by IMDB and available at https://www.imdb.com/interfaces/
    columns:
      - name: person_id
        description: Person ID.
        meta:
          dimension:
            type: string

      - name: imdb_id
        description: IMDB ID of the movie.
        meta:
          dimension:
            type: string


  - name: stg_imdb__movie_ratings
    description: Ratings of movies.
    columns:
      - name: imdb_id
        description: IMDB ID of the movie.
        meta:
          dimension:
            type: string


  - name: stg_imdb__people
    description: Join movies and people info for each movie provided by IMDB and available at https://www.imdb.com/interfaces/
    columns:
      - name: person_id
        description: Person ID.
        meta:
          dimension:
            type: string

      - name: person_name
        description: Person name.
        meta:
          dimension:
            type: string

  - name: stg_imdb__movies
    description: Basic info for each movie provided by IMDB and available at https://www.imdb.com/interfaces/
    columns:
      - name: imdb_id
        description: IMDb ID of the movie.
        meta:
          dimension:
            type: string

      - name: titletype
        description: Type (short, movie, game, video, etc).
        meta:
          dimension:
            type: string

      - name: primarytitle
        description: Title of the movie.
        meta:
          dimension:
            type: string

      - name: originaltitle
        description: Original title of the movie.
        meta:
          dimension:
            type: string

      - name: startyear
        description: Release year (or start year for TV series).
        meta:
          dimension:
            type: number

      - name: runtimeminutes
        description: Runtime in minutes.
        meta:
          dimension:
            type: number
            
      - name: genres
        description: Genres assigned to the movie.
        meta:
          dimension:
            type: string
